import {
  Users,
  Briefcase,
  ShoppingCart,
  Calculator,
  Package,
  KanbanSquare,
  Headphones,
  Factory,
  Megaphone,
  LayoutGrid,
  Building2,
  UserCircle,
  FileText,
  Clock,
  CalendarDays,
  DollarSign,
  Award,
  Plane,
  MessageSquare
} from 'lucide-react';
import { AppView, ModuleConfig } from './types';

export const APP_NAME = "KAA ERP";

// Kaa Brand Logo
import kaaLogo from './kaa_logo.png';
export const KAA_LOGO_URL = kaaLogo;

export const MODULES: ModuleConfig[] = [
  {
    id: AppView.ORGANISATION,
    name: "Organisation",
    description: "Company Structure & Policy",
    icon: Building2,
    color: "text-blue-600",
    bgColor: "bg-blue-100",
  },
  {
    id: AppView.EMPLOYEES,
    name: "Employees",
    description: "People, Approvals & Assets",
    icon: Users,
    color: "text-rose-600",
    bgColor: "bg-rose-100",
  },
  {
    id: AppView.ATTENDANCE,
    name: "Attendance",
    description: "Logs, Shifts & Time Tracking",
    icon: Clock,
    color: "text-cyan-600",
    bgColor: "bg-cyan-100",
  },
  {
    id: AppView.LEAVE,
    name: "Leave",
    description: "Applications, Balances & Calendar",
    icon: CalendarDays,
    color: "text-emerald-600",
    bgColor: "bg-emerald-100",
  },
  {
    id: AppView.PAYROLL,
    name: "Payroll",
    description: "Salary, Payslips & Compliance",
    icon: DollarSign,
    color: "text-violet-600",
    bgColor: "bg-violet-100",
  },
  {
    id: AppView.ESSP,
    name: "ESSP",
    description: "Employee Self Service Portal",
    icon: UserCircle,
    color: "text-teal-600",
    bgColor: "bg-teal-100",
  },
  {
    id: AppView.CRM,
    name: "CRM",
    description: "Customer Relationships & Pipelines",
    icon: Briefcase,
    color: "text-indigo-600",
    bgColor: "bg-indigo-100",
  },
  {
    id: AppView.SALES,
    name: "Sales",
    description: "Quotations, Orders & Invoicing",
    icon: ShoppingCart,
    color: "text-emerald-600",
    bgColor: "bg-emerald-100",
  },
  {
    id: AppView.ACCOUNTING,
    name: "Accounting",
    description: "Financials, Banking & Audit",
    icon: Calculator,
    color: "text-violet-600",
    bgColor: "bg-violet-100",
  },
  {
    id: AppView.INVENTORY,
    name: "Inventory",
    description: "Stock, Logistics & Warehouse",
    icon: Package,
    color: "text-amber-600",
    bgColor: "bg-amber-100",
  },
  {
    id: AppView.PROJECTS,
    name: "Projects",
    description: "Tasks, Timesheets & Planning",
    icon: KanbanSquare,
    color: "text-cyan-600",
    bgColor: "bg-cyan-100",
  },
  {
    id: AppView.HELP_DESK,
    name: "Help Desk",
    description: "Tickets & Customer Support",
    icon: Headphones,
    color: "text-pink-600",
    bgColor: "bg-pink-100",
  },
  {
    id: AppView.MANUFACTURING,
    name: "Manufacturing",
    description: "Work Orders, BOM & PLM",
    icon: Factory,
    color: "text-slate-600",
    bgColor: "bg-slate-100",
  },
  {
    id: AppView.MARKETING,
    name: "Marketing",
    description: "Campaigns & Automation",
    icon: Megaphone,
    color: "text-orange-600",
    bgColor: "bg-orange-100",
  },
  {
    id: AppView.DOCUMENTS,
    name: "Documents",
    description: "Policies, Contracts & Records",
    icon: FileText,
    color: "text-blue-600",
    bgColor: "bg-blue-100",
  },
  {
    id: AppView.RECRUITMENT,
    name: "Recruitment",
    description: "ATS, Hiring & Jobs",
    icon: Briefcase,
    color: "text-amber-600",
    bgColor: "bg-amber-100",
  },
  {
    id: AppView.LOANS,
    name: "Loans & Benefits",
    description: "Advances, Insurance & Claims",
    icon: DollarSign,
    color: "text-emerald-600",
    bgColor: "bg-emerald-100",
  },
  {
    id: AppView.PERFORMANCE,
    name: "Performance",
    description: "Goals, OKRs & Appraisals",
    icon: Award,
    color: "text-violet-600",
    bgColor: "bg-violet-100",
  },
  {
    id: AppView.TRAVEL,
    name: "Travel & Expenses",
    description: "Trips, Bookings & Claims",
    icon: Plane,
    color: "text-rose-600",
    bgColor: "bg-rose-100",
  },
  {
    id: AppView.CHAT,
    name: "Team Chat",
    description: "Direct Messaging & Channels",
    icon: MessageSquare,
    color: "text-indigo-600",
    bgColor: "bg-indigo-100",
  },
];