-- ==============================================================================
-- KAA ERP V1.1 - STABILIZED SCHEMA
-- STRICT RLS & MULTI-TENANCY ENFORCEMENT
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 0. UTILITIES & HELPERS
-- ------------------------------------------------------------------------------

-- Helper to get the current user's company_id securely from profiles
-- Note: This assumes profiles table is populated and linked to auth.users
CREATE OR REPLACE FUNCTION get_my_company_id()
RETURNS UUID AS $$
BEGIN
  RETURN (SELECT company_id FROM profiles WHERE id = auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ------------------------------------------------------------------------------
-- MIGRATION HELPERS (Idempotency)
-- ------------------------------------------------------------------------------
-- Ensure company_id exists on all potential existing tables



-- ------------------------------------------------------------------------------
-- 1. CORE & ORGANISATION
-- ------------------------------------------------------------------------------

-- Profiles (Extends auth.users)
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    email TEXT,
    full_name TEXT,
    company_id UUID NOT NULL, -- The Tenant ID
    role TEXT DEFAULT 'user'
);

-- Departments
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Active',
    head_of_department_id UUID -- Reference to employees(id)
);

-- Locations
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    address TEXT,
    head_of_location_id UUID, -- Reference to employees(id)
    status TEXT DEFAULT 'Active'
);

-- Roles (RBAC Definition)
CREATE TABLE IF NOT EXISTS roles (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    description TEXT,
    permissions TEXT[], -- Array of permission strings e.g. ['hrms.view', 'crm.edit']
    status TEXT DEFAULT 'Active'
);

-- ------------------------------------------------------------------------------
-- 1B. MASTER DATA TABLES (Single Source of Truth)
-- ------------------------------------------------------------------------------

-- Core Organization Masters
CREATE TABLE IF NOT EXISTS org_designations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_employment_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Active'
);

-- HRMS-Specific Masters
CREATE TABLE IF NOT EXISTS org_probation_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    duration_months INTEGER NOT NULL,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_confirmation_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_exit_reasons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);

-- Payroll Masters
CREATE TABLE IF NOT EXISTS org_salary_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    component_type TEXT NOT NULL, -- 'EARNING' or 'DEDUCTION'
    is_taxable BOOLEAN DEFAULT true,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_pay_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    pay_frequency TEXT NOT NULL, -- 'MONTHLY', 'WEEKLY', 'BI_WEEKLY'
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_bank_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    bank_name TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);

-- Leave Masters
CREATE TABLE IF NOT EXISTS org_leave_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    default_balance INTEGER DEFAULT 0,
    is_paid BOOLEAN DEFAULT true,
    requires_approval BOOLEAN DEFAULT true,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_leave_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    leave_type_id BIGINT REFERENCES org_leave_types(id),
    max_consecutive_days INTEGER,
    can_carry_forward BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_holiday_calendar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    holiday_date DATE NOT NULL,
    is_mandatory BOOLEAN DEFAULT true,
    status TEXT DEFAULT 'Active'
);

-- Attendance Masters
CREATE TABLE IF NOT EXISTS org_shift_timings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    grace_period_minutes INTEGER DEFAULT 0,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_weekoff_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    weekdays TEXT[], -- Array of days: ['SATURDAY', 'SUNDAY']
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_attendance_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    affects_salary BOOLEAN DEFAULT true,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_punch_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    min_work_hours NUMERIC DEFAULT 8.0,
    overtime_threshold_hours NUMERIC DEFAULT 9.0,
    status TEXT DEFAULT 'Active'
);

-- Common Attribute Masters
CREATE TABLE IF NOT EXISTS org_faiths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_marital_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_blood_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS org_nationalities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT DEFAULT 'Active'
);

-- ------------------------------------------------------------------------------
-- 2. HRMS MODULE
-- ------------------------------------------------------------------------------

-- Employees (Expanded for Comprehensive HRMS)
CREATE TABLE IF NOT EXISTS employees (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    
    -- System Linking
    profile_id UUID REFERENCES auth.users(id), -- Link to Supabase Auth
    user_account_linked BOOLEAN DEFAULT false,
    role_id UUID REFERENCES roles(id),
    
    -- Basic Information
    employee_code TEXT,
    name TEXT NOT NULL,
    date_of_birth DATE,
    age INTEGER,
    gender TEXT, -- 'Male', 'Female', 'Other'
    faith_id BIGINT REFERENCES org_faiths(id),
    blood_group_id BIGINT REFERENCES org_blood_groups(id),
    marital_status_id BIGINT REFERENCES org_marital_status(id),
    
    -- Contact Information
    personal_mobile TEXT,
    office_mobile TEXT,
    personal_email TEXT,
    office_email TEXT, -- Renamed from 'email' - office email address
    phone TEXT, -- Legacy field, can be deprecated later
    current_address TEXT,
    permanent_address TEXT,
    
    -- Job Information (ALL FROM MASTERS)
    department_id BIGINT REFERENCES departments(id),
    designation_id BIGINT REFERENCES org_designations(id),
    grade_id BIGINT REFERENCES org_grades(id),
    location_id BIGINT REFERENCES locations(id),
    employment_type_id BIGINT REFERENCES org_employment_types(id),
    join_date DATE,
    manager_id UUID REFERENCES employees(id),
    
    -- Legacy fields for backward compatibility
    department TEXT, -- To be deprecated
    designation TEXT, -- To be deprecated
    role TEXT, -- To be deprecated in favor of role_id
    
    -- Payroll Information
    pay_group_id BIGINT REFERENCES org_pay_groups(id),
    salary_amount NUMERIC,
    bank_name TEXT,
    account_number TEXT,
    ifsc_code TEXT,
    
    -- Documents & Media (Supabase Storage URLs)
    profile_photo_url TEXT,
    documents JSONB DEFAULT '[]'::jsonb, -- Array of {type, name, url, uploaded_at}
    
    -- Leave Balance
    leave_balance JSONB DEFAULT '{"casual": 12, "sick": 10, "privilege": 15}'::jsonb,
    
    -- Status
    status TEXT DEFAULT 'Active' -- 'Active', 'On Leave', 'Terminated'
);


-- Attendance Logs
CREATE TABLE IF NOT EXISTS attendance (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    employee_id UUID REFERENCES employees(id),
    date DATE NOT NULL,
    check_in TIMESTAMP WITH TIME ZONE,
    check_out TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'Present', -- 'Present', 'Absent', 'Half Day'
    total_hours NUMERIC DEFAULT 0,
    notes TEXT
);

-- Leave Requests
CREATE TABLE IF NOT EXISTS leaves (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    employee_id UUID REFERENCES employees(id),
    type TEXT NOT NULL, -- 'Casual', 'Sick', etc.
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'Pending', -- 'Pending', 'Approved', 'Rejected'
    manager_comment TEXT,
    approved_by UUID REFERENCES auth.users(id)
);

-- Payroll
CREATE TABLE IF NOT EXISTS payroll (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    employee_id UUID REFERENCES employees(id),
    month TEXT NOT NULL, -- 'YYYY-MM'
    gross_salary NUMERIC NOT NULL,
    deductions NUMERIC DEFAULT 0,
    net_salary NUMERIC NOT NULL,
    status TEXT DEFAULT 'Draft', -- 'Draft', 'Processed', 'Paid'
    payment_date DATE
);

-- Assets
CREATE TABLE IF NOT EXISTS assets (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- 'Hardware', 'Software'
    serial_number TEXT,
    assigned_to UUID REFERENCES employees(id),
    status TEXT DEFAULT 'Available' -- 'Available', 'In Use', 'Repair'
);

-- Help Desk Tickets
CREATE TABLE IF NOT EXISTS tickets (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    employee_id UUID REFERENCES employees(id),
    subject TEXT NOT NULL,
    description TEXT,
    category TEXT DEFAULT 'General',
    priority TEXT DEFAULT 'Medium',
    status TEXT DEFAULT 'Open', -- 'Open', 'In Progress', 'Resolved', 'Closed'
    assigned_to UUID REFERENCES auth.users(id)
);

-- Resignations (Exit Mgmt)
CREATE TABLE IF NOT EXISTS resignations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    employee_id UUID REFERENCES employees(id),
    reason_text TEXT,
    reason_category TEXT,
    proposed_last_working_date DATE,
    status TEXT DEFAULT 'Pending',
    manager_comment TEXT
);

-- Announcements
CREATE TABLE IF NOT EXISTS announcements (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    title TEXT NOT NULL,
    content TEXT,
    type TEXT DEFAULT 'News',
    is_active BOOLEAN DEFAULT true
);

-- ------------------------------------------------------------------------------
-- 3. CRM MODULE
-- ------------------------------------------------------------------------------

-- Contacts
CREATE TABLE IF NOT EXISTS crm_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    role TEXT,
    company TEXT, -- The client company name
    status TEXT DEFAULT 'Active',
    notes TEXT,
    last_contact TIMESTAMP WITH TIME ZONE,
    owner_id UUID REFERENCES auth.users(id)
);

-- Deals (Pipeline)
CREATE TABLE IF NOT EXISTS crm_deals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    title TEXT NOT NULL,
    company TEXT NOT NULL, -- Client Company
    value NUMERIC DEFAULT 0,
    stage TEXT DEFAULT 'LEAD',
    due_date DATE,
    owner_id UUID REFERENCES auth.users(id),
    tag TEXT,
    tag_color TEXT
);

-- Tasks
CREATE TABLE IF NOT EXISTS crm_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    title TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'To Do',
    priority TEXT DEFAULT 'Medium',
    due_date DATE,
    assignee TEXT,
    owner_id UUID REFERENCES auth.users(id)
);

-- ------------------------------------------------------------------------------
-- 4. WORKFLOW & NOTIFICATIONS
-- ------------------------------------------------------------------------------

-- Workflows
CREATE TABLE IF NOT EXISTS workflows (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    description TEXT,
    module TEXT NOT NULL,
    trigger_type TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    level_order_type TEXT DEFAULT 'SEQUENTIAL',
    criteria JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS workflow_levels (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    workflow_id UUID REFERENCES workflows(id) ON DELETE CASCADE,
    level_order INTEGER NOT NULL,
    level_name TEXT NOT NULL,
    approver_type TEXT NOT NULL,
    approver_ids TEXT[],
    approver_logic TEXT DEFAULT 'ANY'
);

CREATE TABLE IF NOT EXISTS workflow_requests (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    workflow_id UUID REFERENCES workflows(id),
    source_id TEXT NOT NULL,
    current_step INTEGER DEFAULT 1,
    status TEXT DEFAULT 'PENDING',
    requester_id UUID REFERENCES auth.users(id)
);

-- Notifications Settings
CREATE TABLE IF NOT EXISTS notification_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    event_type TEXT NOT NULL,
    module TEXT NOT NULL,
    email_enabled BOOLEAN DEFAULT true,
    in_app_enabled BOOLEAN DEFAULT true,
    notify_roles TEXT[]
);

-- Reminders
CREATE TABLE IF NOT EXISTS reminders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    target_filter JSONB DEFAULT '{}'::jsonb,
    schedule_config JSONB DEFAULT '{}'::jsonb,
    recipients_config JSONB DEFAULT '{}'::jsonb,
    is_active BOOLEAN DEFAULT true
);

-- Notifications
CREATE TABLE IF NOT EXISTS notifications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    user_id UUID REFERENCES auth.users(id),
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'INFO',
    link TEXT,
    is_read BOOLEAN DEFAULT false
);

-- ------------------------------------------------------------------------------
-- 5. ROW LEVEL SECURITY (RLS) POLICIES
--    STRATEGY: Isolation via company_id
-- ------------------------------------------------------------------------------

-- Function to enable RLS on a table and add the standard tenant policy
-- Note: Currently we'll just write them out explicitly for clarity and compatibility.

-- 5.1 CORE & ORG RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can only see profiles in their company" ON profiles
    FOR SELECT USING (company_id = get_my_company_id());
-- Allow users to insert/update their OWN profile (special case)
CREATE POLICY "Users can update own profile" ON profiles
    FOR UPDATE USING (id = auth.uid());
CREATE POLICY "Users can insert own profile" ON profiles
    FOR INSERT WITH CHECK (id = auth.uid()); -- Usually handled by triggers, but safe to add

ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON departments
    USING (company_id = get_my_company_id());

ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON locations
    USING (company_id = get_my_company_id());

ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON roles
    USING (company_id = get_my_company_id());

-- 5.1B MASTER DATA RLS
ALTER TABLE org_designations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_designations
    USING (company_id = get_my_company_id());

ALTER TABLE org_grades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_grades
    USING (company_id = get_my_company_id());

ALTER TABLE org_employment_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_employment_types
    USING (company_id = get_my_company_id());

ALTER TABLE org_probation_periods ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_probation_periods
    USING (company_id = get_my_company_id());

ALTER TABLE org_confirmation_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_confirmation_status
    USING (company_id = get_my_company_id());

ALTER TABLE org_exit_reasons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_exit_reasons
    USING (company_id = get_my_company_id());

ALTER TABLE org_salary_components ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_salary_components
    USING (company_id = get_my_company_id());

ALTER TABLE org_pay_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_pay_groups
    USING (company_id = get_my_company_id());

ALTER TABLE org_bank_configs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_bank_configs
    USING (company_id = get_my_company_id());

ALTER TABLE org_leave_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_leave_types
    USING (company_id = get_my_company_id());

ALTER TABLE org_leave_policies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_leave_policies
    USING (company_id = get_my_company_id());

ALTER TABLE org_holiday_calendar ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_holiday_calendar
    USING (company_id = get_my_company_id());

ALTER TABLE org_shift_timings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_shift_timings
    USING (company_id = get_my_company_id());

ALTER TABLE org_weekoff_rules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_weekoff_rules
    USING (company_id = get_my_company_id());

ALTER TABLE org_attendance_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_attendance_status
    USING (company_id = get_my_company_id());

ALTER TABLE org_punch_rules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_punch_rules
    USING (company_id = get_my_company_id());

ALTER TABLE org_faiths ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_faiths
    USING (company_id = get_my_company_id());

ALTER TABLE org_marital_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_marital_status
    USING (company_id = get_my_company_id());

ALTER TABLE org_blood_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_blood_groups
    USING (company_id = get_my_company_id());

ALTER TABLE org_nationalities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON org_nationalities
    USING (company_id = get_my_company_id());


-- 5.2 HRMS RLS
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON employees
    USING (company_id = get_my_company_id());

ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON attendance
    USING (company_id = get_my_company_id());

ALTER TABLE leaves ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON leaves
    USING (company_id = get_my_company_id());

ALTER TABLE payroll ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON payroll
    USING (company_id = get_my_company_id());

ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON assets
    USING (company_id = get_my_company_id());

ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON tickets
    USING (company_id = get_my_company_id());

ALTER TABLE resignations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON resignations
    USING (company_id = get_my_company_id());

ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON announcements
    USING (company_id = get_my_company_id());

-- 5.3 CRM RLS
ALTER TABLE crm_contacts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON crm_contacts
    USING (company_id = get_my_company_id());

ALTER TABLE crm_deals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON crm_deals
    USING (company_id = get_my_company_id());

ALTER TABLE crm_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON crm_tasks
    USING (company_id = get_my_company_id());

-- 5.4 WORKFLOW & NOTIFICATIONS RLS
ALTER TABLE workflows ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON workflows
    USING (company_id = get_my_company_id());

ALTER TABLE workflow_levels ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON workflow_levels
    USING (company_id = get_my_company_id());

ALTER TABLE workflow_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON workflow_requests
    USING (company_id = get_my_company_id());

ALTER TABLE notification_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON notification_settings
    USING (company_id = get_my_company_id());

ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON reminders
    USING (company_id = get_my_company_id());

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON notifications
    USING (company_id = get_my_company_id());

-- ------------------------------------------------------------------------------
-- 6. KUDOS & REWARDS
-- ------------------------------------------------------------------------------

-- Master: Kudos Categories (e.g., "Team Player", "Star Performer")
CREATE TABLE IF NOT EXISTS master_kudos_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    name TEXT NOT NULL,
    description TEXT,
    icon TEXT, -- Lucide icon name or emoji
    points INTEGER DEFAULT 0,
    status TEXT DEFAULT 'Active'
);

-- Transaction: Kudos Given
CREATE TABLE IF NOT EXISTS kudos_rewards (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    sender_id UUID REFERENCES employees(id),
    receiver_id UUID REFERENCES employees(id),
    category_id BIGINT REFERENCES master_kudos_categories(id),
    message TEXT,
    is_public BOOLEAN DEFAULT true
);

-- RLS for Kudos
ALTER TABLE master_kudos_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON master_kudos_categories
    USING (company_id = get_my_company_id());

ALTER TABLE kudos_rewards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON kudos_rewards
    USING (company_id = get_my_company_id());

-- ==============================================================================
-- END OF STABILIZED SCHEMA
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 7. SURVEYS MODULE
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS surveys (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    title TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    expiration_date DATE
);

CREATE TABLE IF NOT EXISTS survey_questions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    survey_id UUID REFERENCES surveys(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    question_type TEXT NOT NULL, -- 'Multiple Choice', 'Text', 'Rating'
    options JSONB DEFAULT '[]'::jsonb, -- e.g. ["Yes", "No"]
    is_required BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS survey_responses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    survey_id UUID REFERENCES surveys(id),
    employee_id UUID REFERENCES employees(id),
    responses JSONB DEFAULT '{}'::jsonb -- Key-Value pair of question_id: answer
);

-- RLS for Surveys
ALTER TABLE surveys ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON surveys USING (company_id = get_my_company_id());

ALTER TABLE survey_questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON survey_questions USING (company_id = get_my_company_id());

ALTER TABLE survey_responses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON survey_responses USING (company_id = get_my_company_id());


-- ------------------------------------------------------------------------------
-- 8. LEARNING PORTAL
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS learning_courses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    title TEXT NOT NULL,
    description TEXT,
    thumbnail_url TEXT,
    total_modules INTEGER DEFAULT 0,
    is_published BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS learning_modules (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    course_id UUID REFERENCES learning_courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    video_url TEXT,
    duration_minutes INTEGER
);

CREATE TABLE IF NOT EXISTS learning_progress (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    company_id UUID NOT NULL DEFAULT get_my_company_id(),
    course_id UUID REFERENCES learning_courses(id),
    employee_id UUID REFERENCES employees(id),
    progress_percentage INTEGER DEFAULT 0,
    completed_module_ids JSONB DEFAULT '[]'::jsonb,
    status TEXT DEFAULT 'Not Started' -- 'In Progress', 'Completed'
);

-- RLS for Learning
ALTER TABLE learning_courses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON learning_courses USING (company_id = get_my_company_id());

ALTER TABLE learning_modules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON learning_modules USING (company_id = get_my_company_id());

ALTER TABLE learning_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant Isolation" ON learning_progress USING (company_id = get_my_company_id());

-- ==============================================================================
-- END OF STABILIZED SCHEMA
-- ==============================================================================
